#!/usr/bin/env bun

import { mkdir, readFile, stat, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { runCodemods } from "../codemods/run-codemods";

const coreRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");

const runtimeFileOrder = [
	"src/zotero.js",
	"src/promise.js",
	"src/debug.js",
	"src/http.js",
	"src/translator.js",
	"src/translators.js",
	"src/repo.js",
	"src/translation/translate.js",
	"src/translation/sandboxManager.js",
	"src/translation/translate_item.js",
	"src/proxy.js",
	"src/tlds.js",
];

async function exists(path: string): Promise<boolean> {
	try {
		await stat(path);
		return true;
	} catch (_e) {
		return false;
	}
}

async function readRuntimeSource(filePath: string, upstreamRoot: string, patchedRoot: string): Promise<string> {
	const patchedPath = join(patchedRoot, filePath);
	if (await exists(patchedPath)) {
		return readFile(patchedPath, "utf-8");
	}
	return readFile(join(upstreamRoot, filePath), "utf-8");
}

function stripCommonJsExports(source: string): string {
	return source.replace(
		/\nif \(typeof module === 'object' && module\.exports\) \{\n\tmodule\.exports = [^;]+;\n\}\n?/g,
		"\n",
	);
}

function renderRuntimeBundle(parts: { filePath: string; source: string }[], upstreamCommit: string | null): string {
	const body = parts
		.map(({ filePath, source }) => {
			return [
				`// ===== ${filePath} =====`,
				stripCommonJsExports(source).trimEnd(),
				";",
			].join("\n");
		})
		.join("\n\n");

	return `/**
 * Auto-generated Zotero translate runtime for Ztractor.
 *
 * Source: https://github.com/zotero/translate
 * Upstream commit: ${upstreamCommit ?? "unknown"}
 *
 * Do not edit this file manually. Run:
 *   bun run build:zotero-runtime
 */

${body}

/**
 * Install the host adapters that let upstream Zotero code run in Ztractor.
 * The runtime remains upstream-owned; adapters provide browser/Node services.
 */
function installZoteroHost(host) {
\tZotero.__ztractorHost = host;
\treturn Zotero;
}

function getZoteroRuntime() {
\treturn Zotero;
}

export { Zotero, ZOTERO_CONFIG, getZoteroRuntime, installZoteroHost };
`;
}

export async function buildZoteroRuntime(): Promise<string> {
	const report = await runCodemods({
		write: true,
		coreRoot,
	});

	const parts = [];
	for (const filePath of runtimeFileOrder) {
		parts.push({
			filePath,
			source: await readRuntimeSource(filePath, report.upstreamRoot, report.outputRoot),
		});
	}

	const outputPath = join(coreRoot, "src/generated/zotero-runtime/index.js");
	const bundle = renderRuntimeBundle(parts, report.upstreamCommit);
	await mkdir(dirname(outputPath), { recursive: true });
	await writeFile(outputPath, bundle, "utf-8");
	return outputPath;
}

if (import.meta.main) {
	buildZoteroRuntime()
		.then((outputPath) => {
			console.log(`Generated ${outputPath}`);
		})
		.catch((error) => {
			console.error(error instanceof Error ? error.message : error);
			process.exit(1);
		});
}
